apiVersion: v1
kind: Service
metadata:
  name: greeter-server
  namespace: examples
  labels:
    app: greeter-server
spec:
  ports:
  - port: 80
    name: grpc
  selector:
    app: greeter-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
  namespace: examples
  labels:
    app: greeter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      labels:
        app: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: ntons/greeter_server:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: LIBRA_API_ACCESS_POINT
          value: 'apiproxy.libra.svc.cluster.local:80'
        ports:
        - containerPort: 80
---
