// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: libra/v1/pub_sub.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubSub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PubSub) Reset() {
	*x = PubSub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub) ProtoMessage() {}

func (x *PubSub) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub.ProtoReflect.Descriptor instead.
func (*PubSub) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0}
}

// 消息
type PubSub_Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 主题
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// 消息ID，发送时候不需要填，收取的时候会自动填充
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// 生产者
	Producer string `protobuf:"bytes,3,opt,name=producer,proto3" json:"producer,omitempty"`
	// 生产时间
	ProduceAt int64 `protobuf:"varint,4,opt,name=produce_at,json=produceAt,proto3" json:"produce_at,omitempty"`
	// 消息载荷
	//
	// Types that are assignable to Value:
	//	*PubSub_Msg_Bin
	//	*PubSub_Msg_Str
	//	*PubSub_Msg_Any
	Value isPubSub_Msg_Value `protobuf_oneof:"value"`
}

func (x *PubSub_Msg) Reset() {
	*x = PubSub_Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_Msg) ProtoMessage() {}

func (x *PubSub_Msg) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_Msg.ProtoReflect.Descriptor instead.
func (*PubSub_Msg) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PubSub_Msg) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PubSub_Msg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PubSub_Msg) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *PubSub_Msg) GetProduceAt() int64 {
	if x != nil {
		return x.ProduceAt
	}
	return 0
}

func (m *PubSub_Msg) GetValue() isPubSub_Msg_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *PubSub_Msg) GetBin() []byte {
	if x, ok := x.GetValue().(*PubSub_Msg_Bin); ok {
		return x.Bin
	}
	return nil
}

func (x *PubSub_Msg) GetStr() string {
	if x, ok := x.GetValue().(*PubSub_Msg_Str); ok {
		return x.Str
	}
	return ""
}

func (x *PubSub_Msg) GetAny() *anypb.Any {
	if x, ok := x.GetValue().(*PubSub_Msg_Any); ok {
		return x.Any
	}
	return nil
}

type isPubSub_Msg_Value interface {
	isPubSub_Msg_Value()
}

type PubSub_Msg_Bin struct {
	Bin []byte `protobuf:"bytes,11,opt,name=bin,proto3,oneof"`
}

type PubSub_Msg_Str struct {
	Str string `protobuf:"bytes,12,opt,name=str,proto3,oneof"`
}

type PubSub_Msg_Any struct {
	Any *anypb.Any `protobuf:"bytes,13,opt,name=any,proto3,oneof"`
}

func (*PubSub_Msg_Bin) isPubSub_Msg_Value() {}

func (*PubSub_Msg_Str) isPubSub_Msg_Value() {}

func (*PubSub_Msg_Any) isPubSub_Msg_Value() {}

type PubSub_SendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  *PubSub_Msg                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Opts *PubSub_SendRequest_Options `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *PubSub_SendRequest) Reset() {
	*x = PubSub_SendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_SendRequest) ProtoMessage() {}

func (x *PubSub_SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_SendRequest.ProtoReflect.Descriptor instead.
func (*PubSub_SendRequest) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PubSub_SendRequest) GetMsg() *PubSub_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PubSub_SendRequest) GetOpts() *PubSub_SendRequest_Options {
	if x != nil {
		return x.Opts
	}
	return nil
}

type PubSub_SendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PubSub_SendResponse) Reset() {
	*x = PubSub_SendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_SendResponse) ProtoMessage() {}

func (x *PubSub_SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_SendResponse.ProtoReflect.Descriptor instead.
func (*PubSub_SendResponse) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 2}
}

type PubSub_ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicStart map[string]*PubSub_ReadRequest_Start `protobuf:"bytes,1,rep,name=topic_start,json=topicStart,proto3" json:"topic_start,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PubSub_ReadRequest) Reset() {
	*x = PubSub_ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_ReadRequest) ProtoMessage() {}

func (x *PubSub_ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_ReadRequest.ProtoReflect.Descriptor instead.
func (*PubSub_ReadRequest) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PubSub_ReadRequest) GetTopicStart() map[string]*PubSub_ReadRequest_Start {
	if x != nil {
		return x.TopicStart
	}
	return nil
}

type PubSub_ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*PubSub_Msg `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *PubSub_ReadResponse) Reset() {
	*x = PubSub_ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_ReadResponse) ProtoMessage() {}

func (x *PubSub_ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_ReadResponse.ProtoReflect.Descriptor instead.
func (*PubSub_ReadResponse) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 4}
}

func (x *PubSub_ReadResponse) GetMsgs() []*PubSub_Msg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type PubSub_ConsumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Ack     string `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *PubSub_ConsumeRequest) Reset() {
	*x = PubSub_ConsumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_ConsumeRequest) ProtoMessage() {}

func (x *PubSub_ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_ConsumeRequest.ProtoReflect.Descriptor instead.
func (*PubSub_ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 5}
}

func (x *PubSub_ConsumeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PubSub_ConsumeRequest) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

type PubSub_ConsumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *PubSub_Msg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PubSub_ConsumeResponse) Reset() {
	*x = PubSub_ConsumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_ConsumeResponse) ProtoMessage() {}

func (x *PubSub_ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_ConsumeResponse.ProtoReflect.Descriptor instead.
func (*PubSub_ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 6}
}

func (x *PubSub_ConsumeResponse) GetMsg() *PubSub_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type PubSub_SendRequest_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTopic bool   `protobuf:"varint,1,opt,name=create_topic,json=createTopic,proto3" json:"create_topic,omitempty"` // 自动创建主题
	MaxLen      int64  `protobuf:"varint,2,opt,name=max_len,json=maxLen,proto3" json:"max_len,omitempty"`                // 主题保存的消息数量
	MinId       string `protobuf:"bytes,3,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`                    // 主题保存的最小ID
}

func (x *PubSub_SendRequest_Options) Reset() {
	*x = PubSub_SendRequest_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_SendRequest_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_SendRequest_Options) ProtoMessage() {}

func (x *PubSub_SendRequest_Options) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_SendRequest_Options.ProtoReflect.Descriptor instead.
func (*PubSub_SendRequest_Options) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *PubSub_SendRequest_Options) GetCreateTopic() bool {
	if x != nil {
		return x.CreateTopic
	}
	return false
}

func (x *PubSub_SendRequest_Options) GetMaxLen() int64 {
	if x != nil {
		return x.MaxLen
	}
	return 0
}

func (x *PubSub_SendRequest_Options) GetMinId() string {
	if x != nil {
		return x.MinId
	}
	return ""
}

type PubSub_ReadRequest_Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to At:
	//	*PubSub_ReadRequest_Start_AfterId
	//	*PubSub_ReadRequest_Start_SinceTimestampMillis
	At isPubSub_ReadRequest_Start_At `protobuf_oneof:"at"`
}

func (x *PubSub_ReadRequest_Start) Reset() {
	*x = PubSub_ReadRequest_Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libra_v1_pub_sub_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubSub_ReadRequest_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub_ReadRequest_Start) ProtoMessage() {}

func (x *PubSub_ReadRequest_Start) ProtoReflect() protoreflect.Message {
	mi := &file_libra_v1_pub_sub_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub_ReadRequest_Start.ProtoReflect.Descriptor instead.
func (*PubSub_ReadRequest_Start) Descriptor() ([]byte, []int) {
	return file_libra_v1_pub_sub_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (m *PubSub_ReadRequest_Start) GetAt() isPubSub_ReadRequest_Start_At {
	if m != nil {
		return m.At
	}
	return nil
}

func (x *PubSub_ReadRequest_Start) GetAfterId() string {
	if x, ok := x.GetAt().(*PubSub_ReadRequest_Start_AfterId); ok {
		return x.AfterId
	}
	return ""
}

func (x *PubSub_ReadRequest_Start) GetSinceTimestampMillis() int64 {
	if x, ok := x.GetAt().(*PubSub_ReadRequest_Start_SinceTimestampMillis); ok {
		return x.SinceTimestampMillis
	}
	return 0
}

type isPubSub_ReadRequest_Start_At interface {
	isPubSub_ReadRequest_Start_At()
}

type PubSub_ReadRequest_Start_AfterId struct {
	// 指定ID之后(不包含指定ID)
	AfterId string `protobuf:"bytes,1,opt,name=after_id,json=afterId,proto3,oneof"`
}

type PubSub_ReadRequest_Start_SinceTimestampMillis struct {
	// 指定毫秒时间戳开始
	SinceTimestampMillis int64 `protobuf:"varint,2,opt,name=since_timestamp_millis,json=sinceTimestampMillis,proto3,oneof"`
}

func (*PubSub_ReadRequest_Start_AfterId) isPubSub_ReadRequest_Start_At() {}

func (*PubSub_ReadRequest_Start_SinceTimestampMillis) isPubSub_ReadRequest_Start_At() {}

var File_libra_v1_pub_sub_proto protoreflect.FileDescriptor

var file_libra_v1_pub_sub_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x5f, 0x73,
	0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e,
	0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x07,
	0x0a, 0x06, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x1a, 0xc1, 0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x5f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x41,
	0x74, 0x12, 0x12, 0x0a, 0x03, 0x62, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x03, 0x62, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x28, 0x0a, 0x03, 0x61, 0x6e, 0x79,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x03,
	0x61, 0x6e, 0x79, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0xcd, 0x01, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x69, 0x62, 0x72,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75,
	0x62, 0x53, 0x75, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x1a, 0x5c,
	0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07,
	0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d,
	0x61, 0x78, 0x4c, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x1a, 0x0e, 0x0a, 0x0c,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0xa3, 0x02, 0x0a,
	0x0b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x0b,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62,
	0x53, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x62, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x66, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x36, 0x0a, 0x16, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x14, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x42, 0x04, 0x0a, 0x02, 0x61, 0x74, 0x1a,
	0x61, 0x0a, 0x0f, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x75, 0x62, 0x53, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x38, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x53,
	0x75, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x3d, 0x0a, 0x0e,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x1a, 0x39, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x2e, 0x4d, 0x73,
	0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xed, 0x01, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x53, 0x75,
	0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64,
	0x12, 0x1c, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x53,
	0x75, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a,
	0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x75, 0x62, 0x53, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x12, 0x50, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x12,
	0x1f, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x53, 0x75,
	0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x53,
	0x75, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x74, 0x6f, 0x6e, 0x73, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_libra_v1_pub_sub_proto_rawDescOnce sync.Once
	file_libra_v1_pub_sub_proto_rawDescData = file_libra_v1_pub_sub_proto_rawDesc
)

func file_libra_v1_pub_sub_proto_rawDescGZIP() []byte {
	file_libra_v1_pub_sub_proto_rawDescOnce.Do(func() {
		file_libra_v1_pub_sub_proto_rawDescData = protoimpl.X.CompressGZIP(file_libra_v1_pub_sub_proto_rawDescData)
	})
	return file_libra_v1_pub_sub_proto_rawDescData
}

var file_libra_v1_pub_sub_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_libra_v1_pub_sub_proto_goTypes = []interface{}{
	(*PubSub)(nil),                     // 0: libra.v1.PubSub
	(*PubSub_Msg)(nil),                 // 1: libra.v1.PubSub.Msg
	(*PubSub_SendRequest)(nil),         // 2: libra.v1.PubSub.SendRequest
	(*PubSub_SendResponse)(nil),        // 3: libra.v1.PubSub.SendResponse
	(*PubSub_ReadRequest)(nil),         // 4: libra.v1.PubSub.ReadRequest
	(*PubSub_ReadResponse)(nil),        // 5: libra.v1.PubSub.ReadResponse
	(*PubSub_ConsumeRequest)(nil),      // 6: libra.v1.PubSub.ConsumeRequest
	(*PubSub_ConsumeResponse)(nil),     // 7: libra.v1.PubSub.ConsumeResponse
	(*PubSub_SendRequest_Options)(nil), // 8: libra.v1.PubSub.SendRequest.Options
	(*PubSub_ReadRequest_Start)(nil),   // 9: libra.v1.PubSub.ReadRequest.Start
	nil,                                // 10: libra.v1.PubSub.ReadRequest.TopicStartEntry
	(*anypb.Any)(nil),                  // 11: google.protobuf.Any
}
var file_libra_v1_pub_sub_proto_depIdxs = []int32{
	11, // 0: libra.v1.PubSub.Msg.any:type_name -> google.protobuf.Any
	1,  // 1: libra.v1.PubSub.SendRequest.msg:type_name -> libra.v1.PubSub.Msg
	8,  // 2: libra.v1.PubSub.SendRequest.opts:type_name -> libra.v1.PubSub.SendRequest.Options
	10, // 3: libra.v1.PubSub.ReadRequest.topic_start:type_name -> libra.v1.PubSub.ReadRequest.TopicStartEntry
	1,  // 4: libra.v1.PubSub.ReadResponse.msgs:type_name -> libra.v1.PubSub.Msg
	1,  // 5: libra.v1.PubSub.ConsumeResponse.msg:type_name -> libra.v1.PubSub.Msg
	9,  // 6: libra.v1.PubSub.ReadRequest.TopicStartEntry.value:type_name -> libra.v1.PubSub.ReadRequest.Start
	2,  // 7: libra.v1.PubSubService.Send:input_type -> libra.v1.PubSub.SendRequest
	4,  // 8: libra.v1.PubSubService.Read:input_type -> libra.v1.PubSub.ReadRequest
	6,  // 9: libra.v1.PubSubService.Consume:input_type -> libra.v1.PubSub.ConsumeRequest
	3,  // 10: libra.v1.PubSubService.Send:output_type -> libra.v1.PubSub.SendResponse
	5,  // 11: libra.v1.PubSubService.Read:output_type -> libra.v1.PubSub.ReadResponse
	7,  // 12: libra.v1.PubSubService.Consume:output_type -> libra.v1.PubSub.ConsumeResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_libra_v1_pub_sub_proto_init() }
func file_libra_v1_pub_sub_proto_init() {
	if File_libra_v1_pub_sub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_libra_v1_pub_sub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_SendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_SendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_ConsumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_ConsumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_SendRequest_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libra_v1_pub_sub_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubSub_ReadRequest_Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_libra_v1_pub_sub_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PubSub_Msg_Bin)(nil),
		(*PubSub_Msg_Str)(nil),
		(*PubSub_Msg_Any)(nil),
	}
	file_libra_v1_pub_sub_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*PubSub_ReadRequest_Start_AfterId)(nil),
		(*PubSub_ReadRequest_Start_SinceTimestampMillis)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libra_v1_pub_sub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libra_v1_pub_sub_proto_goTypes,
		DependencyIndexes: file_libra_v1_pub_sub_proto_depIdxs,
		MessageInfos:      file_libra_v1_pub_sub_proto_msgTypes,
	}.Build()
	File_libra_v1_pub_sub_proto = out.File
	file_libra_v1_pub_sub_proto_rawDesc = nil
	file_libra_v1_pub_sub_proto_goTypes = nil
	file_libra_v1_pub_sub_proto_depIdxs = nil
}
